# Generated by Django 4.0b1 on 2021-11-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_band_about_band_img_venue_about_venue_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
